name:                 for-go
version:              0.1.0.0
visibility:           public
id:                   for-go-0.1.0.0-inplace
key:                  for-go-0.1.0.0-inplace
license:              BSD-3-Clause
maintainer:           zyzhuo@outlook.com
author:               VhRvo
category:             Language
abi:                  inplace
exposed:              True
exposed-modules:      Magic
import-dirs:
    /Users/zhangyongzhuo/Desktop/Workplace/Languages/Haskell/for_go/dist-newstyle/build/aarch64-osx/ghc-9.4.8/for-go-0.1.0.0/build

library-dirs:
    /Users/zhangyongzhuo/Desktop/Workplace/Languages/Haskell/for_go/dist-newstyle/build/aarch64-osx/ghc-9.4.8/for-go-0.1.0.0/build

library-dirs-static:
    /Users/zhangyongzhuo/Desktop/Workplace/Languages/Haskell/for_go/dist-newstyle/build/aarch64-osx/ghc-9.4.8/for-go-0.1.0.0/build

dynamic-library-dirs:
    /Users/zhangyongzhuo/Desktop/Workplace/Languages/Haskell/for_go/dist-newstyle/build/aarch64-osx/ghc-9.4.8/for-go-0.1.0.0/build

data-dir:
    /Users/zhangyongzhuo/Desktop/Workplace/Languages/Haskell/for_go/.

hs-libraries:         HSfor-go-0.1.0.0-inplace
depends:              base-4.17.2.1
haddock-interfaces:
    /Users/zhangyongzhuo/Desktop/Workplace/Languages/Haskell/for_go/dist-newstyle/build/aarch64-osx/ghc-9.4.8/for-go-0.1.0.0/doc/html/for-go/for-go.haddock

haddock-html:
    /Users/zhangyongzhuo/Desktop/Workplace/Languages/Haskell/for_go/dist-newstyle/build/aarch64-osx/ghc-9.4.8/for-go-0.1.0.0/doc/html/for-go
